modLoader="javafml" #mandatory

loaderVersion="[47,)" #mandatory

license="${mod_license}"

[[mods]] #mandatory

modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

authors="${mod_authors}" #optional

description='''${mod_description}'''

[[dependencies.${mod_id}]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="placebo"
   mandatory=true
   versionRange="[${placeboVersion},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="apothic_attributes"
   mandatory=false
   versionRange="[${attributeslibVersion},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="jade"
   mandatory=false
   versionRange="[11.0.0,12.0.0)"
   ordering="AFTER"
   side="CLIENT"

[[dependencies.${mod_id}]]
   modId="tacz"
   mandatory=false
   versionRange="[1.1.0,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${mod_id}]]
   modId="jei"
   mandatory=false
   versionRange="[15.0.0,)"
   ordering="NONE"
   side="CLIENT"

[[dependencies.${mod_id}]]
   modId="slashblade"
   mandatory=false
   versionRange="[1.1.0,)"
   ordering="NONE"
   side="BOTH"