modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="hamstercore"
version="1.0.0"
displayName="HamsterCore"
description="Core functionality for the Hamster mod suite"
authors="xlxyvergil"

[[dependencies.hamstercore]]
modId="forge"
mandatory=true
versionRange="[47.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.hamstercore]]
modId="placebo"
mandatory=true
versionRange="[8.6.0,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.hamstercore]]
modId="jade"
mandatory=false
versionRange="[11.13,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.hamstercore]]
modId="tacz"
mandatory=false
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.hamstercore]]
modId="jei"
mandatory=false
versionRange="[15.0.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.hamstercore]]
modId="slashblade"
mandatory=false
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"